### ISSUE TITLE
Potential issue with MaxForceErrorHandler 

### ISSUE THREAD

**Issue by gpetretto** [materialsproject/custodian#103]
I believe that there is a problem with the way the `MaxForceErrorHandler` is implemented. 
The correct method only acts on the EDIFFG key, leaving the EDIFF unchanged. This might be fine if this handler is called only once and if there is a large enough factor between EDIFF and EDIFFG. However, for example I ended up in a situation in which this handler was applied multiple times, causing the value of EDIFFG to go below that of EDIFF, which is clearly a bad configuration.

In general I would say that it would preferable to keep the same ratio between EDIFF and EDIFFG. i.e. EDIFF could be multiplied by 0.5 as well. If this seems unsuitable, at the very least it should be checked that EDIFFG does not go below EDIFF.

**Comment by shyamd** [comment]
Actually, it looks like the error handler doesn't even do what the docstring says it does. I didn't realize this changed EDIFFG. I always assumed it was just modifying EDIFF and allowing the default EDIFFG = 10*EDIFF ratio built into VASP.

I personally don't even use this error handler, since it's not really an error, but a badly parameterized input. If you want force convergence, the jobs should be set up to run energy convergence and then force convergence, instead of ad-hoc'ing it with this.

**Comment by shyuep** [comment]
I agree that this error handler is used in the ancient days of MP when resource constraints meant that we lived with no EDIFFG setting. Technically, the best solution is to get EDIFF and EDIFFG correct from the start like Shyam says.

**Comment by gpetretto** [comment]
While I agree with you that a proper way of handling the calculations would be to set EDIFF and EDIFFG  correctly, I would like to highlight a few points:

* I would say that the handler in custodian should be either correct or not present at all. And in its current form it does not seem to be working properly.
* This handler is used by default in atomate for the optimization workflow (from the `max_force_threshold` option). In fact I had no interest in converging the forces in my calculations and I realized that it was enabled only once jobs started to fail because of it. So chances are that some atomate users are actually using it without being fully aware.

**Comment by mkhorton** [comment]
The `max_force_threshold` in atomate is actually problematic for another reason; every time this handler gets hit it counts as an error and can easily trigger the custodian max errors parameter (which defaults to 5) even though these are not errors per se. Agreed the handler should either be fixed or removed.

**Comment by shyuep** [comment]
I am happy to delete this. Someone will need to remove the use in atomate.
