### ISSUE TITLE
why isn't "copy_magmom" defaulted to True in double_relaxation_run()?

### ISSUE THREAD

**Issue by computron** [materialsproject/custodian#14]
Custodian contains a built-in function to generate double relaxation vasp jobs. Is there a reason to not default the copy_magmom to True in this case?

Similar for full_opt_run (although that is not used by Materials Project)

**Comment by wmdrichards** [comment]
Afaik, no. But it is still somewhat experimental.

On Oct 6, 2015, at 4:47 PM, Anubhav Jain <notifications@github.com> wrote:

Custodian contains a built-in function to generate double relaxation vasp
jobs. Is there a reason to not default the copy_magmom to True in this case?

Similar for full_opt_run (although that is not used by Materials Project)

—
Reply to this email directly or view it on GitHub
<https://github.com/materialsproject/custodian/issues/14>.

**Comment by computron** [comment]
Ok. I also forgot that if there is a CHGCAR with magnetization, MAGMOM is anyway ignored:

http://cms.mpi.univie.ac.at/vasp/vasp/MAGMOM_tag.html

Maybe that that is the assumption here, i.e. don't worry about changing MAGMOM since it won't be used anyway due to CHGCAR. Sounds reasonable, closing the issue.

**Comment by wmdrichards** [comment]
It's a little unclear to me how vasp reads the chgcar when the fft grid or
kpoints changes between relaxation runs. It seems to not be much of an
issue in practice but sometimes the magnetization changes on the restart.

On Oct 7, 2015, at 10:13 AM, Anubhav Jain <notifications@github.com> wrote:

Closed #14 <https://github.com/materialsproject/custodian/issues/14>.

—
Reply to this email directly or view it on GitHub
<https://github.com/materialsproject/custodian/issues/14#event-429167476>.

**Comment by shyuep** [comment]
I suspect VASP simply interpolates the charge in real space.
It is more of an issue when we have bad initial structures. But for those, I would argue it is probably better off to reinitialize the magmom anyway.
