### ISSUE TITLE
Some errors are not detected in VASP6

### ISSUE THREAD

**Issue by rkingsbury** [materialsproject/custodian#156]
## System

* Custodian version: latest master branch as of 2020-11-01
* Python 3.8
* VASP 6.1.1

## Summary

`VaspErrorHandler` fails to detect certain error categories in VASP 6 that were detected properly in VASP 5. This appears to be a result of formatting changes associated with the error messages. My understanding is that custodian reads stdout line-by-line, but some of the error messages have been reformatted in such a way that they now break across multiple lines and hence are not caught.

See example below for the `point_group` error. I have also observed this for `inv_rot_mat` message, and I suspect it could affect other handlers as well.

## Error message

VASP6:

```
 -----------------------------------------------------------------------------
|                                                                             |
|     EEEEEEE  RRRRRR   RRRRRR   OOOOOOO  RRRRRR      ###     ###     ###     |
|     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
|     E        R     R  R     R  O     O  R     R     ###     ###     ###     |
|     EEEEE    RRRRRR   RRRRRR   O     O  RRRRRR       #       #       #      |
|     E        R   R    R   R    O     O  R   R                               |
|     E        R    R   R    R   O     O  R    R      ###     ###     ###     |
|     EEEEEEE  R     R  R     R  OOOOOOO  R     R     ###     ###     ###     |
|                                                                             |
|     VERY BAD NEWS! internal error in subroutine IBZKPT: Error: point        |
|     group operation missing 2                                               |
|                                                                             |
|       ---->  I REFUSE TO CONTINUE WITH THIS SICK JOB ... BYE!!! <----       |
|                                                                             |
 -----------------------------------------------------------------------------
```

VASP5:
```
 VERY BAD NEWS! internal error in subroutine IBZKPT:
 Error: point group operation missing       2
```

The `point_group` error looks for the entire message on a single line:
```
"point_group": ["Error: point group operation missing"],
```

## Suggested solution (if known)

It's not clear to me what the best solution is. Ideally we would move away from reading one line at a time and instead detect the entire string, regardless of where a line break occurs, but that may be difficult in practice. Alternatively, perhaps we need to shorten the error messages that are detected so that custodian will catch them in both VASP5 and VASP6.

**Comment by shyuep** [comment]
I don't think we can read the entire file and make it robust. In the end, even if I read the entire file, the string is now "Error: point     | \n | group operation missing 2" or somethnig to that effect. I suggest you just shorten the error message for now.

**Comment by mkhorton** [comment]
VASP uses a common subroutine to print a lot of these error messages (`tutor.F` I think), so this probably affects a lot of other errors too in VASP6.
