### ISSUE TITLE
Yaml logs

### ISSUE THREAD

**Issue by janosh** [materialsproject/custodian#187]
How about adding an option to write logs to `custodian.yaml` instead of  `custodian.json`? More readable IMO and fits more logs onto one screen. Yaml is slower to write presumably but won't be the bottleneck.

**Comment by shyuep** [comment]
The logs are fairly short in themselves that I don't see this as a major issue. But I have no objection if you want to make it happen. In any case, I think just setting Custodian.LOG_FILE to custodian.yaml will already automatically write it out in yaml since we are using monty to dump.

**Comment by mkhorton** [comment]
I would vote against this. Better to have one and only one format, in my own opinion. I don't love JSON for all purposes but at least it's consistent and only one file to look for.

Btw @janosh, if you're struggling with readability I can highly recommend the command line tool `jq`.

**Comment by janosh** [comment]
@mkhorton Fair point. Closing this issue. You mentioned `jq` during the MP seminar. Neat little tool! I do use it occasionally but mostly prefer to view files in an editor.

**Comment by shyuep** [comment]
I just want to say that having a default JSON is good enough for me. But if someone else (not within MP) wants to use YAML as the format and have their infrastructure set up that way, I don't see why we need to ban that. As long as the code changes do not affect default behavior that MP uses, it doesn't matter to me.
