### ISSUE TITLE
Override INCAR settings for each job in double_relaxation_run()

### ISSUE THREAD

**Issue by janosh** [materialsproject/custodian#203]
Could we add a kwarg to `VaspJob.double_relaxation_run()` to override the INCAR settings of either 1st, 2nd or both runs?

@arosen93 suggested to set `ISMEAR=0` for 1st job only to avoid `Tetrahedron method fails (number of k-points < 4)`.

https://github.com/materialsproject/custodian/blob/89098059cd327802007a00a1b48f0cc09ea78627/custodian/vasp/jobs.py#L285-L349

**Comment by shyuep** [comment]
This is already supported. There is a YAML job def format that allows yin to specify an arbitrary sequence of runs with arbitrary overrides at each step. Look at the cstdn script.

**Comment by arosen93** [comment]
For that error specifically, I'm somewhat surprised that one of the handler options is to change the k-point grid (via KSPACING). Seems like we shouldn't be touching the number of kpts or k-spacing for the purposes of job compatibility. Just my $0.02.

**Comment by janosh** [comment]
@shyuep Thanks for the pointer. Right now I'm using `atomate` so to use a YAML spec file, I'd replace the `RunVaspCustodian` task with the FireWorks `ScriptTask` and tell it to execute `cstdn run double-relax.yml`?

**Comment by shyuep** [comment]
@janosh You don't have to do that. The yaml format is just a way to specify an arbitrary multi-step workflow easily. You can easily write a code equivalent in atomate, similar to the code in the VaspJob.double_relaxation_run convenience method. 

E.g.,

```
[
            VaspJob(
                vasp_cmd,
                final=False,
                suffix=".relax1",
                auto_npar=auto_npar,
                auto_continue=auto_continue,
                settings_override={"dict": "INCAR", "action": {"_set": {"ISMEAR": 0}},
            ),
            VaspJob(
                vasp_cmd,
                final=True,
                backup=False,
                suffix=".relax2",
                auto_npar=auto_npar,
                auto_continue=auto_continue,
                settings_override={"dict": "INCAR", "action": {"_set": {"ISMEAR": -5}},
            ),
        ]
```

would achieve what you want.

**Comment by janosh** [comment]
@shyuep Thanks. That looks good but then how do I wrap those two jobs in `RunVaspCustodian` cause I do want to keep all the handlers and validators it applies. It's 150 lines long so wouldn't want to copy all that code into my workflow.

`RunVaspCustodian` only accepts a `job_type`

```txt
job_type: (str) - choose from "normal" (default), "double_relaxation_run" (two consecutive
            jobs), "full_opt_run" (multiple optimizations), and "neb"
```

Wouldn't it be more flexible to also accept a list of jobs?

**Comment by shyuep** [comment]
I am not sure what the RunVaspCustodian task does. But I would suggest that it be made more flexible to handle any list of jobs and handlers and validators. That's what the `Custodian.from_spec` method does.

**Comment by janosh** [comment]
`RunVaspCustodian` is called a total of 23 times across the `atomate` code base so I think it's the central piece of interaction with `custodian` which itself is only called 7 times.

When I opened this PR I thought `RunVaspCustodian` came from `custodian` but seeing that it's defined in `atomate`,

https://github.com/hackingmaterials/atomate/blob/a5ff51707607d76b65f897b5d5effbe80bc51a2a/atomate/vasp/firetasks/run_calc.py#L73-L306

will check with @itsshawnzhang and @computron over there if we can make it more flexible.
