### ISSUE TITLE
Suggestion: Try to rerun the job when errors occur in postprocessing

### ISSUE THREAD

**Issue by ganfisher** [materialsproject/custodian#207]
## Summary
In current custodian, there is no any handler for ValidationError and ReturnCodeError in postprcessing of jobs. In my experience, such errors are usually caused by accidental factors, and very likely to be fixed by just rerunning the job.

## Example code
Take the handling of ValidationError as an example.
In custodian/custodian.py (the '_run_job method'), replace the code
```python
            if not has_error:
                for v in self.validators:
                    if v.check():
                        self.run_log[-1]["validator"] = v
                        s = f"Validation failed: {v.__class__.__name__}"
                        raise ValidationError(s, True, v)
            ...
```

with
```python
            if not has_error:
                #set a tag
                tag = True
                for v in self.validators:
                    if v.check():
                        self.acc_total_errors += 1
                        tag = False
                        self.run_log[-1]["validator"] = v
                        s = f"Validation failed: {v.__class__.__name__}"
                        #just use the 'max_errors' a threshold
                        if self.acc_total_errors < self.max_errors:
                            job.terminate()
                            #skip the other
                            continue
                        else:
                            raise ValidationError(s, True, v)
             ...
             if tag:
                 job.postprocess()
                 return
             else:
                 #just try to rerun the job
                 continue
```

**Comment by shyuep** [comment]
That isn't really true. There can be other factors that cause a job to fail a validation, e.g., bad inputs. Even if it is cause by some external factor, e.g., a bad io, it is likely that external factor will be present again in a rerun. What you are proposing essentially will cause an infinite loop until `self.max_errors`. That will burn resources for no reason. 

Errors should have a well-defined form and should be caught by handlers. If you desire that the code loops job attempts until self-max_errors, you can write your own handler that does exactly the same checks as the validator and does no fixes and just rerun the job. I wouldn't recommend it, but it is entirely up to you how to work with the resources you have.

**Comment by ganfisher** [comment]
> That isn't really true. There can be other factors that cause a job to fail a validation, e.g., bad inputs. Even if it is cause by some external factor, e.g., a bad io, it is likely that external factor will be present again in a rerun. What you are proposing essentially will cause an infinite loop until `self.max_errors`. That will burn resources for no reason.
> 
> Errors should have a well-defined form and should be caught by handlers. If you desire that the code loops job attempts until self-max_errors, you can write your own handler that does exactly the same checks as the validator and does no fixes and just rerun the job. I wouldn't recommend it, but it is entirely up to you how to work with the resources you have.

Thanks, I've got that.
