### ISSUE TITLE
Suggestion: disable algo_tet VASP handler by default

### ISSUE THREAD

**Issue by utf** [materialsproject/custodian#221]
#180 and #202 introduced an error handler to catch calculations with `ALGO = All` and `ISMEAR = -5` based on a warning in the OUTCAR file.

Currently, this error handler means it is a pain to run high quality hybrid density of states (you need to create a pre-converged WAVECAR) and then run `ALGO=DAMPED` + tetrahedron method.

I'm curious if this error handler was added due to experience or just based on the warning itself. In my experience running hybrid of states calculations (on 300+ systems) I've never seen this warning lead to a crash.

I would suggest disabling this error message by default. If we want to keep it enabled, the fix should only be applied if the calculation actually failed and not if the calculation completes successfully as is currently the case.

@arosen93 what are your thoughts?

**Comment by utf** [comment]
Thanks for the quick response!

>  My only question is: is it "okay" to use ALGO = All, ISMEAR=-5, and a hybrid calculation?

Yes definitely. As long as the calculation converges there shouldn't be any issue (bearing in mind all the usual caveats on relaxing with tetrahedron method).

> my suggestion would be to retain the check but only apply it if it fails per your latter suggestion.

I think this is the best way to proceed. I'll update the error handler.

**Comment by arosen93** [comment]
> I think this is the best way to proceed. I'll update the error handler.

Great, thanks! I also was left unsatisfied with the current approach and hybrids, so this makes me much happier that it's okay to do.

**Comment by arosen93** [comment]
According to my notes and comments in the handler, `grad_not_orth` can coincide with `algo_tet`, in which the `algo_tet` error handler should take priority over the `grad_not_orth` handler, as this will resolve both instances.

I want to make sure the current `grad_not_orth` fix is only applied if `algo_tet` is not concurrently present. When opening your PR, would you mind going to https://github.com/materialsproject/custodian/blob/master/custodian/vasp/handlers.py#L506 and changing `if "grad_not_orth" in self.errors` to `if "grad_not_orth" in self.errors and "algo_tet" not in self.errors`? Thanks.
