### ISSUE TITLE
AMIN error handler unnecessarily applied

### ISSUE THREAD

**Issue by utf** [materialsproject/custodian#229]
Sometimes VASP prints the following warning for large cells:
```
 -----------------------------------------------------------------------------
|                                                                             |
|           W    W    AA    RRRRR   N    N  II  N    N   GGGG   !!!           |
|           W    W   A  A   R    R  NN   N  II  NN   N  G    G  !!!           |
|           W    W  A    A  R    R  N N  N  II  N N  N  G       !!!           |
|           W WW W  AAAAAA  RRRRR   N  N N  II  N  N N  G  GGG   !            |
|           WW  WW  A    A  R   R   N   NN  II  N   NN  G    G                |
|           W    W  A    A  R    R  N    N  II  N    N   GGGG   !!!           |
|                                                                             |
|     One of the lattice vectors is very long (>50 A), but AMIN is rather     |
|     large. This can spoil convergence since charge sloshing might occur     |
|     along the long lattice vector. If problems with convergence are         |
|     observed, try to decrease AMIN to a smaller value (e.g. 0.01).          |
|     Note: This warning only applies if the self-consistency cycle is        |
|     used.                                                                   |
|                                                                             |
 -----------------------------------------------------------------------------
```

This is printed whether or not the system fails to converge and is only a warning that the system MIGHT not converge.

However, the "amin" error handler in custodian is applied whether or not there was a problem with convergence. This means, calculations that still converged fine are thrown out at the end, leading to a waste of computer time.

Can the amin handler be updated so that it is only applied if there are also convergence issues?

Alternatively, since this error message is printed immediately before the SCF cycle, can the error message be caught immediately before any time is wasted on the calculation.

**Comment by shyuep** [comment]
By all means. I agree.

**Comment by utf** [comment]
I've noticed that there is already an error handler that catches calculations that are not converging (`NonConvergingErrorHandler`). This handler changes AMIN to a lower value already. 

Can I just remove the explicit AMIN handler as the same fix will get applied if the calculation actually suffers from convergence issues, which is what the warning is all about anyway.
