### ISSUE TITLE
Failed to terminate an outdated job and create a new one at same time.

### ISSUE THREAD

**Issue by specter119** [materialsproject/custodian#25]
## System

* Custodian version: 0.8.8
* Python version: 2.7.11
* OS version: Red Hat Enterprise Linux Server release 6.3 (Santiago) 
* MPenv version: sjtu branch
* pymatgen version: 3.5.0 (develop model)
* Fireworks version: 1.2.7 (develop model)
* MPWorks version: 0.1dev0.1
* VASP version: 5.4.1.05Feb16 (also tried 5.3.3)

## Summary

1. vasp calculation with custodian failed to terminate an outdated job when the now job has already created.
2. to create 5 jobs at most belonging to a single firework.

## Example code

```python
from mpworks.submission.submission_mongo import SubmissionMongoAdapter
from pymatgen.matproj.snl import StructureNL
from pymatgen.core.structure import Structure
from pymatgen.transformations.standard_transformations import SubstitutionTransformation

# set submission db
sma         = SubmissionMongoAdapter.auto_load()
# read structure from POSCAR file.
bs_struc    = Structure.from_file("POSCAR")
# some substitution, then bs_struc→re_struc
snl         = StructureNL(re_struc, 'KeLiu <specter119@gmail.com>')
sma.submit_snl(snl, 'specter119@gmail.com', parameters=None)
```

then `go_submissions` and `qlaunch`

```sh
qlaunch -r rapidfire --nlaunches infinite -m 4 --sleep 100 -b 10000
```

## Error message

fireworks: Cu1_La1_Te2--GGA_optimize_structure_(2x)
Cu1_La1_Te2--GGA_opt-11690.error

```
INFO:custodian.custodian:Run started at 2016-04-20 14:24:05.227027 in /lustre/home/umjzhh-1/launcher/layered_material/ycute2/substitution_01stRun/block_2016-04-18-11-18-03-912778/launcher_2016-04-20-01-37-05-453043.
INFO:custodian.custodian:Custodian running on Python version 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 1. Errors thus far = 0.
INFO:root:Running mpirun -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.1.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'too_few_bands'], u'actions': [{u'action': {u'_set': {u'NBANDS': 28}}, u'dict': u'INCAR'}]}
INFO:root:Backing up run to error.2.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.PositiveEnergyErrorHandler object at 0x2af3687fcf90>, u'errors': [u'Positive energy'], u'actions': [{u'action': {u'_set': {u'ALGO': u'Normal'}}, u'dict': u'INCAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 2. Errors thus far = 2.
INFO:root:Running mpirun -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.3.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'eddrmm'], u'actions': [{u'action': {u'_set': {u'POTIM': 0.25}}, u'dict': u'INCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'CHGCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'WAVECAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 3. Errors thus far = 3.
INFO:root:Running mpirun -n 32 vasp
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 19
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 23
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 14
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 17
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 8
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 11
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 21
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 12
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 15
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 22
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 7
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 10
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 16
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 18
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 29
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 13
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 20
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 25
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 5
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 31
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 27
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 24
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 28
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 26
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 30
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 9
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.4.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'zpotrf', u'eddrmm'], u'actions': [{u'action': {u'_set': {u'ISYM': 0, u'POTIM': 0.125}}, u'dict': u'INCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'CHGCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'WAVECAR'}, {u'action': {u'_set': {u'POTIM': 0.125}}, u'dict': u'INCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'CHGCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'WAVECAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 4. Errors thus far = 4.
INFO:root:Running mpirun -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.5.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'subspacematrix'], u'actions': [{u'action': {u'_set': {u'LREAL': False}}, u'dict': u'INCAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 5. Errors thus far = 5.
INFO:root:Running mpirun -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.6.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'subspacematrix'], u'actions': [{u'action': {u'_set': {u'LREAL': False}}, u'dict': u'INCAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Max errors reached.
ERROR:custodian.custodian:MaxErrors
INFO:custodian.custodian:Logging to custodian.json...
INFO:custodian.custodian:Run ended at 2016-04-20 15:47:38.863389.
INFO:custodian.custodian:Run completed. Total time taken = 1:23:33.636362.
Traceback (most recent call last):
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/rocket.py", line 213, in run
    m_action = t.run_task(my_spec)
  File "/lustre/home/umjzhh-1/kl_me2/codes/MPWorks/mpworks/firetasks/custodian_task.py", line 115, in run_task
    custodian_out = c.run()
  File "/lustre/home/umjzhh-1/kl_me2/codes/custodian/custodian/custodian.py", line 221, in run
    .format(self.total_errors, ex))
RuntimeError: 6 errors reached: (CustodianError(...), u'MaxErrors'). Exited...
INFO:rocket.launcher:Rocket finished
```

the relevant SLURM status:

```
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode
------------ ---------- ---------- ---------- ---------- ---------- --------
11690        Cu1_La1_T+        cpu acct-umjz+         32  COMPLETED      0:0
11690.batch       batch            acct-umjz+         32  COMPLETED      0:0
11690.0       pmi_proxy            acct-umjz+          2  COMPLETED      0:0
11690.1       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.2       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.3       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.4       pmi_proxy            acct-umjz+          2     FAILED      7:0
```
## Suggested solution (if known)

* I have no idea, but I want know which is the relevant code of  "terminate_func"?

## Files

<If input files are needed for the error, please copy and paste them here.>

```
```

**Comment by shyuep** [comment]
This is not a problem to be reported in custodian. Pls report this to Fireworks.


Shyue Ping

On April 27, 2016 at 1:55:08 AM, specter119 (notifications@github.com) wrote:

System

Custodian version: 0.8.8
Python version: 2.7.11
OS version: Red Hat Enterprise Linux Server release 6.3 (Santiago)
Mpenv version: sjtu branch
pymatgen version: 3.5.0 (develop model)
Fireworks version: 1.2.7 (develop model)
MPWorks version: 0.1dev0.1
VASP version: 5.4.1.05Feb16 (also tried 5.3.3)
Summary

vasp calculation with custodian failed to terminate an outdated job when the now job has already created.
to create 5 jobs at most belonging to a single fireworks.
Example code

from mpworks.submission.submission_mongo import SubmissionMongoAdapter
from pymatgen.matproj.snl import StructureNL
from pymatgen.core.structure import Structure
from pymatgen.transformations.standard_transformations import \
    SubstitutionTransformation

__author__  = 'Ke Liu'
__version__ = '0.1'
__email__   = 'specter119@gmail.com'
__date__    = 'Apr 07, 2016'

# set submission db
sma         = SubmissionMongoAdapter.auto_load()

# read strucuture from POSCAR file.
bs_struc    = Structure.from_file("POSCAR")

# substitution for xy to avoid xx etc.
init_struc  = SubstitutionTransformation({"Y":"He"}).\
              apply_transformation(bs_struc)
init_struc  = SubstitutionTransformation({"Cu":"Ne"}).\
              apply_transformation(init_struc)
init_struc  = SubstitutionTransformation({"Te":"Ar"}).\
              apply_transformation(init_struc)

# list elements with +3,+1,-2 common_oxidaton_state
els_n3      = "list some +3 elements"
els_n1      = "list some +1 elements"
els_p2      = "list some -2 elements"

# substitute for "X"
for el_x in els_n3:
    tempy_struc               = SubstitutionTransformation({"He":el_x}).\
                                apply_transformation(init_struc)
    # substitute for "Y"
    for el_y in els_n1:
        if (el_y!=el_x):
            tempz_struc       = SubstitutionTransformation({"Ne":el_y}).\
                                apply_transformation(tempy_struc)
            # substitute for "Z"
            for el_z in els_p2:
                if (el_z!=el_x and el_z!=el_y):
                     re_struc = SubstitutionTransformation({"Ar":el_z}).\
                                apply_transformation(tempz_struc)
                     snl      = StructureNL(re_struc, \
                                            'KeLiu <specter119@gmail.com>')
                     sma.submit_snl(snl, 'specter119@gmail.com', \
                                    parameters=None)
then go_submissions and qlaunch

qlaunch -r rapidfire --nlaunches infinite -m 4 --sleep 100 -b 10000
Personal settings:

Here is my_qadapter.yaml

_fw_name: CommonAdapter
_fw_q_type: SLURM
rocket_launch: rlaunch -c /lustre/home/umjzhh-1/kl_me2/config/config_SjtuPi singleshot
nodes: 2
ntasks_per_node: 16
walltime: '24:00:00'
queue: cpu
account: null
job_name: null
pre_rocket: null
post_rocket: null
logdir: /lustre/home/umjzhh-1/kl_me2/config/logs
I also modified MPWorks/mpworks/workflows/wf_settings.py(line 10~11) to adapt the requirements of our supercomputing center.

QA_VASP = {'nnodes': 2}
QA_VASP_SMALL = {'nnodes': 2, 'walltime': '24:00:00'}  # small walltime jobs
Error message

fireworks: Cu1_La1_Te2--GGA_optimize_structure_(2x)
Cu1_La1_Te2--GGA_opt-11690.error

INFO:custodian.custodian:Run started at 2016-04-20 14:24:05.227027 in /lustre/home/umjzhh-1/launcher/layered_material/ycute2/substitution_01stRun/block_2016-04-18-11-18-03-912778/launcher_2016-04-20-01-37-05-453043.
INFO:custodian.custodian:Custodian running on Python version 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 1. Errors thus far = 0.
INFO:root:Running mpirun -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.1.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'too_few_bands'], u'actions': [{u'action': {u'_set': {u'NBANDS': 28}}, u'dict': u'INCAR'}]}
INFO:root:Backing up run to error.2.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.PositiveEnergyErrorHandler object at 0x2af3687fcf90>, u'errors': [u'Positive energy'], u'actions': [{u'action': {u'_set': {u'ALGO': u'Normal'}}, u'dict': u'INCAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 2. Errors thus far = 2.
INFO:root:Running mpirun -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.3.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'eddrmm'], u'actions': [{u'action': {u'_set': {u'POTIM': 0.25}}, u'dict': u'INCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'CHGCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'WAVECAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 3. Errors thus far = 3.
INFO:root:Running mpirun -n 32 vasp
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 19
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 23
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 14
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 17
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 8
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 11
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 21
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 12
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 15
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 22
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 6
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 7
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 10
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 16
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 18
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 29
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 13
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 20
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 25
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 5
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 31
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 27
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 24
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 28
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 26
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 30
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 9
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.4.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'zpotrf', u'eddrmm'], u'actions': [{u'action': {u'_set': {u'ISYM': 0, u'POTIM': 0.125}}, u'dict': u'INCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'CHGCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'WAVECAR'}, {u'action': {u'_set': {u'POTIM': 0.125}}, u'dict': u'INCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'CHGCAR'}, {u'action': {u'_file_delete': {u'mode': u'actual'}}, u'file': u'WAVECAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 4. Errors thus far = 4.
INFO:root:Running mpirun -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.5.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'subspacematrix'], u'actions': [{u'action': {u'_set': {u'LREAL': False}}, u'dict': u'INCAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Starting job no. 1 (VaspJob) attempt no. 5. Errors thus far = 5.
INFO:root:Running mpirun -n 32 vasp
INFO:custodian.custodian:Terminating job
INFO:root:Backing up run to error.6.tar.gz.
ERROR:custodian.custodian:{u'handler': <custodian.vasp.handlers.VaspErrorHandler object at 0x2af3687fce10>, u'errors': [u'subspacematrix'], u'actions': [{u'action': {u'_set': {u'LREAL': False}}, u'dict': u'INCAR'}]}
INFO:custodian.custodian:VaspJob.run has completed. Checking remaining handlers
INFO:custodian.custodian:Max errors reached.
ERROR:custodian.custodian:MaxErrors
INFO:custodian.custodian:Logging to custodian.json...
INFO:custodian.custodian:Run ended at 2016-04-20 15:47:38.863389.
INFO:custodian.custodian:Run completed. Total time taken = 1:23:33.636362.
Traceback (most recent call last):
  File "/lustre/home/umjzhh-1/kl_me2/codes/fireworks/fireworks/core/rocket.py", line 213, in run
    m_action = t.run_task(my_spec)
  File "/lustre/home/umjzhh-1/kl_me2/codes/MPWorks/mpworks/firetasks/custodian_task.py", line 115, in run_task
    custodian_out = c.run()
  File "/lustre/home/umjzhh-1/kl_me2/codes/custodian/custodian/custodian.py", line 221, in run
    .format(self.total_errors, ex))
RuntimeError: 6 errors reached: (CustodianError(...), u'MaxErrors'). Exited...
INFO:rocket.launcher:Rocket finished

the relevant SLURM status:

       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode
------------ ---------- ---------- ---------- ---------- ---------- --------
11690        Cu1_La1_T+        cpu acct-umjz+         32  COMPLETED      0:0
11690.batch       batch            acct-umjz+         32  COMPLETED      0:0
11690.0       pmi_proxy            acct-umjz+          2  COMPLETED      0:0
11690.1       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.2       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.3       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.4       pmi_proxy            acct-umjz+          2     FAILED      7:0

Suggested solution (if known)

Files

<contents of file 1>

**Comment by specter119** [comment]
After detecting error, the job shall stop and incar shall be modified and new calculation shall be resubmitted.But right now old calculations were not terminated though new calculation with modified incar submitted, which leads to overloading computer nodes.
