### ISSUE TITLE
Failed to terminate an outdated calculation but create a new one at same time (within a single firework).

### ISSUE THREAD

**Issue by specter119** [materialsproject/custodian#26]
## System

* Custodian version: 0.8.8
* Python version: 2.7.11
* OS version: Red Hat Enterprise Linux Server release 6.3 (Santiago)
* MPenv version: sjtu branch
* pymatgen version: 3.5.0 (develop model)
* Fireworks version: 1.2.7 (develop model)
* MPWorks version: 0.1dev0.1
* VASP version: 5.4.1.05Feb16 (also tried 5.3.3)

## Summary

1. vasp calculation with custodian failed to terminate an calculation outdated job when the now job has already created.
2. to create 5 jobs at most belonging to a single firework.

After detecting error, the job shall stop and incar shall be modified and new calculation shall be resubmitted.But right now old calculations were not terminated though new calculation with modified incar submitted, which leads to overloading computer nodes.

I have no idea, but I want know which is the relevant code of "terminate_func"?

## Example code and Error message is showed in #25

**Comment by shyuep** [comment]
I think you are confusing a few things. Custodian does not ALWAYS terminate a job. When it finds that an error can be corrected, it will modify parameters and resubmit. terminate_func is specified by the handlers, to deal with unrecoverable errors. 

As for **another** job being run, this is not a Custodian issue. It is a Fireworks issue. Custodian only deals with each job as a standalone thing. There is no workflow (other than internal error correction) built in. Pls contact @computron to solve it.

**Comment by computron** [comment]
@shyuep everything in the message suggests it is within a single Firework (e.g. the title of this thread). I don't think multiple Fireworks are being created. Rather it seems the complaint is that custodian will restart a new VASP call while the older VASP call is still running. @specter119, please confirm. Note that when @specter119 says "job" I am interpreting his statements to mean "VASP invocation" and not PBS job or Firework.

**Comment by specter119** [comment]
@computron Thank you, "job" means a **sub** SLURM job (as well as a VASP invocation) which is show as in the following table. (e.g. 11690.1, 11690.2). It belongs to the whole SLRUM job or Firework.

```sh
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode
------------ ---------- ---------- ---------- ---------- ---------- --------
11690        Cu1_La1_T+        cpu acct-umjz+         32  COMPLETED      0:0
11690.batch       batch            acct-umjz+         32  COMPLETED      0:0
11690.0       pmi_proxy            acct-umjz+          2  COMPLETED      0:0
11690.1       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.2       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.3       pmi_proxy            acct-umjz+          2     FAILED      7:0
11690.4       pmi_proxy            acct-umjz+          2     FAILED      7:0
```

as @shyuep  say
>  When it finds that an error can be corrected, it will modify parameters and resubmit. 

for example. If 11690.0 (the first sub SLURM job) FIALED, it will be terminated and custodian will modify parameters and resubmit. BUT, the next sub SLRUM job (maybe 11690.1 or still 11690.0, I am not clear) should should start to run but the pervious job should be already terminated.

But in my current situation, until the whole SLURM job (Firework) FAILED, all of the sub SLURM jobs (VASP invocations) are running. so I turn to you for help. @shyuep  

Thanks for your help @computron @shyuep

**Comment by computron** [comment]
Sorry but I don't know much about **sub** SLURM jobs (how they are created, invoked, etc). When we run with SLURM is it is without any sub-jobs (that I know of) and things run pretty smoothly

**Comment by shyuep** [comment]
I don't know what this issue is about or even how to begin to solve this. I suggest you debug and come up with a proposed solution first. One option is to set the max_errors to 1. In that case, any error will trigger a job termination. But if you are doing that, there really isn't a point to using custodian.....

**Comment by specter119** [comment]
@computron @shyuep would you please show me your running SLURM job infos (e.g. `sacct -u USER_NAME`)? I don't know what is the right status of VASP invocations with SLURM.  Thank you !

**Comment by computron** [comment]
The running jobs looks something like this:

193676       Na3_O6_V3+ matgen_reg    matcomp         32    RUNNING      0:0 
193676.0           vasp               matcomp         32    RUNNING      0:0

(there are no other sub-jobs)

Sorry, but this is about the extent that I can help with this problem. If you have further questions, you might try:
https://groups.google.com/forum/#!forum/matproj-develop

**Comment by specter119** [comment]
@computron Thank you.
