### ISSUE TITLE
[BUG] Issue with LargeSigmaHandler

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/custodian#266]
https://github.com/materialsproject/custodian/blob/f7dc11a15aee43e57cc8b52bf4a39ed7c5fd1e63/custodian/vasp/handlers.py#L1254C3-L1254C3

Currently, if no ISMEAR is found in the INCAR file, the LargeSigmaHandler uses a value of 0. However, the default ISMEAR from VASP is actually 1. This should be changed.

**Comment by arosen93** [comment]
@matthewkuner: Thanks for reporting. I'll submit a PR shortly.
