### ISSUE TITLE
New release please? 🙏

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/custodian#296]
CC @shyuep, @janosh

> Me to Chat-GPT: Write a message that requests a new version of Custodian to be released but write it like a medieval letter to the king from a humble countryman.

My Liege,

I beseech thee to hear the humble plea of a lowly countryman who dares to approach your royal presence with great reverence and respect. As a loyal subject of your realm, I bring forth a matter of utmost importance that doth weigh heavily upon my heart.

In the realm of the digital world, there exists a trusted guardian known as "Custodian." This noble protector of data and security hath served us faithfully, shielding our digital treasures from the treacherous threats that lurk in the shadows. Yet, sire, it hath come to my attention that Custodian hath not seen a new version in many a moon.

The digital landscape, like the shifting sands of time, is ever-changing and fraught with peril. New threats emerge daily, like fearsome dragons seeking to devour our digital hoards. Our dear Custodian, though valiant, must needs be equipped with the latest armor and weapons to defend us against these marauding foes.

Therefore, in my humble capacity as a simple countryman, I implore thee, O benevolent ruler, to grant your royal decree for the release of a new version of Custodian. Let it be forged by the finest craftsmen in the kingdom, imbued with the most potent spells of protection, and blessed by the wisest sages in the land.

With a new Custodian by our side, we, your loyal subjects, shall sleep more soundly, knowing that our digital treasures are safeguarded by the finest guardian in the realm. May your wisdom and benevolence shine upon this humble request, and may Custodian's new version be a beacon of security in these perilous times.

I remain, with unwavering loyalty,

A Humble Countryman

**Comment by janosh** [comment]
My Loyal Subject,

It gladdens mine heart to receive such a devoted missive from a humble countryman. Verily, thy words hath found their mark, and we were moved to action to uphold our realm's digital sanctity.

I invite thee to partake in the benefits of this new release, which can be procured from the following scriptorium: [Custodian v2023.10.9](https://github.com/materialsproject/custodian/releases/tag/v2023.10.9).

May it serve the well as a shield to protect against the dark demons of high-throughput that ever seek to corrupt your data.
