### ISSUE TITLE
Add test for `NonConvergingErrorHandler`

### ISSUE THREAD

**Issue by janosh** [materialsproject/custodian#300]
I just noticed we currently have zero test coverage for `NonConvergingErrorHandler`. Sorry @fyalcin, didn't mean to imply you should write a new error handler test from scratch.

@Andrew-S-Rosen @matthewkuner Would either of you know where best to get reference files that match the `NonConvergingErrorHandler.check` conditions?

```py
class NonConvergingErrorHandler(ErrorHandler):
    """
    Check if a run is hitting the maximum number of electronic steps at the
    last nionic_steps ionic steps (default=10). If so, change ALGO using a
    multi-step ladder scheme or kill the job.
    """

    def check(self):
        """Check for error."""
        vi = VaspInput.from_directory(".")
        n_elm = vi["INCAR"].get("NELM", 60)  # number of electronic steps
        try:
            oszicar = Oszicar(self.output_filename)
            elec_steps = oszicar.electronic_steps
            if len(elec_steps) > self.nionic_steps:
                return all(len(e) == n_elm for e in elec_steps[-(self.nionic_steps + 1) : -1])
        except Exception:
            pass
        return False
```

_Originally posted by @janosh in https://github.com/materialsproject/custodian/issues/297#issuecomment-1793843008_

**Comment by matthewkuner** [comment]
Personally, I would just manually modify the file to have extra electronic/ionic steps, or change the parameter for nionic_steps to be lower
