### ISSUE TITLE
Terminate Function Seems Not Working Properly With SLURM

### ISSUE THREAD

**Issue by xhqu1981** [materialsproject/custodian#31]
This issue only matters when using Vasp Monitors and only when running jobs in a SLURM environmental. It seems to originate from the Popen.terminate() python API. If a job terminates normally, all the function works properly. However, once a VASP job is killed by Popen.terminate(), which would be true if the Monitor finds an error, new VASP job will never be able to run. The error message is "Unable to create job step: Job/step already completing or completed". The power of custodian is **fully prohibited** in this situation.

How do you know whether you are affected? If the success rate of recent calculation degrades, probably you are already affected.

I reproduced the error using a simple python script without custodian and asked NERSC staff to fix it. They confirmed the issue and promised to investigate it. However, it has already been two weeks I didn't get any update. As a precaution, I think we should consider the possibility they are not able fix it in short term.

I have an alternative to walk-around this issue in my fork. The point is to use "scancel" to kill VASP job. This method releases the resource successfully while Popen.terminate() doesn't. It seems to be working fine for the last two weeks. However, it makes the custodian code more complicated and environment dependent. I am not sure whether it is a good idea to merge this piece of code to the main repository.

**Comment by shyuep** [comment]
No, pls do not merge. Custodian should have not system specific dependence.

Have you tried using sys.exit() instead? Does that effectively kill the job in SLURM?

**Comment by xhqu1981** [comment]
I am sorry I might confused you.

I didn't try sys.exit(). As far as I can understand it is to end the current process, right? The issue I am talking about is to end another process --- "srun", which is analogue to "mpirun". The relevant code in at line 516 of custodian.custodian.Custodian._do_check(). i.e. The following code:

`if terminate_func is not None and h.is_terminating:logger.info("Terminating job")`
 `terminate_func()`
`#make sure we don't terminate twice
                        terminate_func = None
                    d = h.correct()`

**Comment by xhqu1981** [comment]
Change the VASP exit code in case of error will definitely work. However, without modifying the VASP source code, there is no way for me to change the exit code from VASP.

**Comment by shyuep** [comment]
How about Popen.kill()? Does that work? This sends a SIGKILL instead of SIGTERM to the child process.

**Comment by xhqu1981** [comment]
I tested both of them. Same issue.

**Comment by xhqu1981** [comment]
Oh. No. I tested SIGINT, not SIGKILL. Testing SIGKILL now.

**Comment by xhqu1981** [comment]
Just realize that kill() and SIGKILL are the same thing. I tested kill() and signal(SIGINT)

**Comment by shyuep** [comment]
No, the current function is p.terminate. Python can also do p.kill. You are saying that both do not work?

**Comment by xhqu1981** [comment]
All of the following doesn't work:
`p.terminate()`
`p.kill()`
`p.send_signal(signal.SIGINT)`

**Comment by shyuep** [comment]
ok, but if I replace p.terminate with sys.exit?
That will exit the python process, which will kill all jobs by definition.

**Comment by xhqu1981** [comment]
All of the above terminates the current VASP job. And the command to submit new VASP job get execute, however, just infinitely waiting for VASP to start.

**Comment by xhqu1981** [comment]
Yes. If replace p.terminate with sys.exit(), it will kill the whole job. The bad thing is we also lose the opportunity to fix the job, which is main purpose of custodian.

**Comment by xhqu1981** [comment]
In such situation there would no difference with running a bare-bone VASP command. And I still want the power of custodian.

**Comment by shyuep** [comment]
I added a terminate_func in the custodian constructor. That will allow you to define your own termination function in lieu of p.terminate. So you can try doing that instead.

**Comment by shyuep** [comment]
Note that all you have to do is to code a different slurm_terminate function in MPWorks. Then pass it into the code that runs custodian.__init__. In general, I do not wish to introduce system dependence. I;d rather leave MP staff and MPWorks to deal with system dependence problems.

**Comment by xhqu1981** [comment]
A typo. What I did

**Comment by xhqu1981** [comment]
Well it's similar to what I didn't. Since the constructor provides the
opportunity to specify termination function. I will move the termination
function to MPWorks now.

Thanks.
