### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/custodian#330]
### Problem

I would like to adapt the atomate2 workflows with the new run command for LOBSTER.

### Proposed Solution

Release of a new custodian version compatible with the latest pymatgen release.

### Alternatives

No real alternatives.

Thank you!

**Comment by JaGeo** [comment]
(cc @shyuep @janosh )

**Comment by JaGeo** [comment]
Just wanted to follow up on this. It would be great to have this out. Thanks in advance.

**Comment by shyuep** [comment]
Done

**Comment by JaGeo** [comment]
Thank you very much, @shyuep !
