### ISSUE TITLE
[BUG]: The "tet" handler for VASP seems to catch different errors under one label

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/custodian#338]
### Problem

https://github.com/materialsproject/custodian/blob/bc9ecbb5c41fbc7a67b880af6cd804cba52ecd05/custodian/vasp/handlers.py#L71-L78

These are not all the same errors and are therefore not handled all in the same way. For instance, "Tetrahedron method fails (number of k-points < 4)" is a clear error that can only be resolved by changing ISMEAR or the number of k-points. However, "Fatal error: unable to match k-point" is related to symmetry according to the [VASP forum](https://www.vasp.at/forum/viewtopic.php?t=489).

Tagging @esoteric-ephemera since it's part of the discussion.

### Proposed Solution

Split this up into distinct errors, even if some subset of those errors end up having the same fix.

**Comment by shyuep** [comment]
I am assuming this issue is closed?

**Comment by Andrew-S-Rosen** [comment]
Yes!
