### ISSUE TITLE
[Bug]: The corrected INCAR is not stored in the right location when setting a custom `directory`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/custodian#340]
In #317 by @zulissimeta, support for a custom `directory` keyword argument was added to the `Custodian` class so that it did not always have to run in the current working directory.

However, it appears this behavior has an important bug with VASP. When a VASP error occurs, Custodian updates the INCAR (as expected). However, this updated INCAR is *not* stored in the specified `directory` but is instead stored in the current working directory. This means that the calculation itself is never actually corrected. It will keep failing since the INCAR remains the same.

Any failing calculation will reproduce this behavior with the following minimal example, assuming your VASP files are stored in a directory `test` and you are running this script from outside of that directory:

```python
from custodian import Custodian
from custodian.vasp.jobs import VaspJob
from custodian.vasp.handlers import (
    FrozenJobErrorHandler,
    IncorrectSmearingHandler,
    KspacingMetalHandler,
    LargeSigmaHandler,
    MeshSymmetryErrorHandler,
    NonConvergingErrorHandler,
    PositiveEnergyErrorHandler,
    PotimErrorHandler,
    StdErrHandler,
    UnconvergedErrorHandler,
    VaspErrorHandler,
    WalltimeHandler,
)

handlers = [VaspErrorHandler(), FrozenJobErrorHandler(), IncorrectSmearingHandler(), LargeSigmaHandler(), MeshSymmetryErrorHandler(), NonConvergingErrorHandler(), PositiveEnergyErrorHandler(), PotimErrorHandler(), StdErrHandler(), UnconvergedErrorHandler(), WalltimeHandler(), KspacingMetalHandler()]

jobs = [VaspJob(["vasp_std"])] # change this to your VASP executable
c = Custodian(handlers, jobs, directory="test")
c.run()
```

For a specific reproduction:

1. Download `reproduction.zip` below
2. Run `unzip reproduction.zip`
3. Add a POTCAR for Cu in `reproduction/test`, like `PAW_PBE Cu 22Jun2005` (not shared here since it is proprietary)
4. Run `python test_custodian.py` using `reproduction` as the working directory.

What you'll see is the following after it runs:

```
/reproduction
--- INCAR <-- this should be in the `test` directory
--- run_custodian.py
--- test
------- all the other files
```

[reproduction.zip](https://github.com/user-attachments/files/16074374/reproduction.zip)

CC'ing @honghuikim who reported anomalous behavior in https://github.com/Quantum-Accelerators/quacc/issues/2323, motivating me to make this minimal example.

### Version

v2024.6.24

### Which OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by JaGeo** [comment]
Ah. I just ran into rhw `ISMEAR=-5` and <4 kpoints issue and was confused that this wasn't corrected (bur did not look into it in detail)
