### ISSUE TITLE
VasprunXMLValidator Error: Missing vasprun.xml

### ISSUE THREAD

**Issue by YuanbinLiu** [materialsproject/custodian#347]
I am encountering an issue where the VasprunXMLValidator in custodian raises an error because the vasprun.xml file is missing. This issue occurs sporadically when I submit a large number of VASP jobs using atomate2 and fireworks. From the logs, it appears that VASP does not even start properly, yet custodian attempts to validate the run, leading to the following traceback:

> [ERROR] Failed to load vasprun.xml
Traceback (most recent call last):
  File "/path/to/custodian/vasp/validators.py", line 33, in check
    load_vasprun(os.path.join(directory, "vasprun.xml"))
  File "/path/to/custodian/utils.py", line 79, in __call__
    result = self.func(*args, **kwargs)
  File "/path/to/custodian/vasp/io.py", line 21, in load_vasprun
    return Vasprun(filepath, **vasprun_kwargs)
  File "/path/to/pymatgen/io/vasp/outputs.py", line 309, in __init__
    with zopen(filename, mode="rt") as file:
  File "/path/to/monty/io.py", line 54, in zopen
    return open(filename, *args, **kwargs)  # pylint: disable=R1732
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/vasprun.xml'

Could custodian be enhanced to detect when a VASP job fails due to submission system issues and automatically attempt to resubmit the job? This would help in cases where VASP doesn't start, preventing these errors and improving job reliability.

Additionally, any advice on how to structure job submissions to minimize these occurrences would be greatly appreciated.

Thank you for your assistance! 

### Version

v2024.4.18

### Which OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by shyuep** [comment]
I don't think there is a way to handle issues in submission systems in a robust manner. We have seldom encountered this. It all really depends on how the IT sets up the cluster and submission.
