### ISSUE TITLE
Custodian Monitor Not Working with terminate_on_nonzero_returncode=True

### ISSUE THREAD

**Issue by xhqu1981** [materialsproject/custodian#42]
## System

* Custodian version: master branch, revision _af15bda_ and _5f0e8b_
* Python version: 3.5.2
* OS version: Cray XC40

## Summary

This test compares two revisions in the master branch: 1) "_5f0e8b9_" which is after adding the return code exception raising code, 2) "_af15bda_" which before adding return code logic. The "run_vasp" is command is used to perform the test. No workflows messed up with the test, only a simple SLURM script and custodian package were involved.

The most important message is from "run.log" file.

1) With revision "_5f0e8b9_":

After "{'errors': ['eddrmm']...", the custodian says "Job return code is 137. Terminating...".

2) With revision "_af15bda_":

After "After "{'errors': ['eddrmm']...", the custodian says "Starting job no. 1 (VaspJob) attempt no. 2". There are other issues which are specific to my environment and are already solved, which I don't think will affect the conclusions. The bottom line is that with the old code is trying to fix the error while the new code exits prematurely.

## Example code

```
module load vasp/5.4.1
run_vasp -c "srun -n 32 vasp_std" static
```

## Error message

```
"Job return code is 137. Terminating..." vs "Starting job no. 1 (VaspJob) attempt no. 2".
```

## Suggested solution (if known)

* When both Monitors and terminate_on_nonzero_returncode=True are requested, disable either of them.
* Document that the Monitor won't work if terminate_on_nonzero_returncode is set to true, otherwise, the users will have the illusion that they still have Custodian Monitor to fix VASP errors.

## Files

[cus_5f0e8b9_after_rc.tar.gz](https://github.com/materialsproject/custodian/files/664917/cus_5f0e8b9_after_rc.tar.gz)

[cus_af15bda_before_rc.tar.gz](https://github.com/materialsproject/custodian/files/664918/cus_af15bda_before_rc.tar.gz)

**Comment by computron** [comment]
Note - I think detection of a non_zero return code should simply set the "has_error" flag to True rather than actually raise an error. This would give Handlers a chance to fix nonzero return codes rather than simply exiting.

**Comment by shyuep** [comment]
Guys guys, read the code properly. As I said before, Custodian *by default* exits with a non-zero error code. But if you set terminate_on_nonzero_return_code = False, then it will not exit. Otherwise, this is ignored. A handler should check the inputs/outputs and deal with the siutation.

**Comment by xhqu1981** [comment]
I know. But I don't think everyone who wants Custodian Monitor knows to set terminate_on_nonzero_return_code = False.

**Comment by shyuep** [comment]
Ok, you cannot have your cake and eat it. Either Custodian exits with a non-zero code, or it doesn't. As I said, we cannot pass codes to the handlers. The handlers depend on actually having detecting errors in the output. I can certainly set the default to be False.

**Comment by xhqu1981** [comment]
@shyuep What I used in the example is just a "run_vasp" command, which is relevant to the users without significant programming knowledge, if only terminate_on_nonzero_return_code = False can make custodain work, we are actually forcing them to know the details of the API.

**Comment by xhqu1981** [comment]
I am not suggesting set the default to be False. As a design principle, the code itself is expected to logically consistent. Monitors and terminate_on_nonzero_return_code are not compatible with each other. I am suggesting that when both of them are true, the custodian either reminders the users to remove all the Monitors or set terminate_on_nonzero_return_code to False. I don't have a strong opinion what should default value to be, but I am expecting the code to be self-consistent.

**Comment by computron** [comment]
>> I can certainly set the default to be False.

If there is no other change made, then I think this is helpful for at least everyone using custodian for VASP (nearly everyone...) to retain the old behavior. Otherwise you will certainly hear from other people as well who are finding that custodian doesn't fix the errors anymore.

>> Ok, you cannot have your cake and eat it.

Well for me, having the cake and eating it would amount to:

- if there is a zero return code, custodian acts like it did before (this should already be the case)
- if there is a nonzero return code, custodian again acts like it did before. The only exception is that if you have a nonzero return code AND no errors were fixed by any handler, then actually you terminate the job instead of proceeding. Practically, this would be simple and straightforward to implement, and amount to checking the return code only inside the validation loop of custodian.py (~line 414) and making the return code a validator. As I understand it, this validation loop only runs if no errors were detected or handled.

**Comment by computron** [comment]
(i.e., I see the returncode check as a "validator" step rather than as a monitor or handler-type step)

**Comment by computron** [comment]
Ok one more comment - in the above view, the returncode (if enabled) is just checking your "final" answer to make sure it makes sense. It doesn't meddle with your intermediate computations.

**Comment by xhqu1981** [comment]
Thanks.
