### ISSUE TITLE
improvement to max errors with multi-job

### ISSUE THREAD

**Issue by computron** [materialsproject/custodian#51]
When reporting bugs/issues, please supply the following information. If this 
is a feature request, please simply state the requested feature.

## System

* Custodian version: master

## Summary

* If I have a 2-step structure relaxation, and the first relaxation hits MAX_ERRORs, the 2nd job still seems to perform some of the maintenance steps of "copying files to relax1 extension".
* This makes it more difficult to realize that the 2nd job never actually ran. e.g., the directory contains both "OUTCAR.relax1" and "OUTCAR". Usually, that means that OUTCAR is for the 2nd job and OUTCAR.relax1 is for the first job, and the second job failed. In this case, the two files are identical since the first job hit max errors.
* see uploaded file error.tar.gz (CHGCAR/WAVECAR/PROCAR removed) for an example where the first relaxation failed due to max errors

## Files

[error.tar.gz](https://github.com/materialsproject/custodian/files/924479/error.tar.gz)

**Comment by computron** [comment]
Here's also an example where, despite relax1 hitting 5 (=max) errors, relax2 seems to at least briefly start. Not sure why relax2 is starting at all?

Note that the error files don't seem to show max_errors being hit, but the launch entry in the FireWorks database shows that this error was thrown by custodian - the Fireworks action's stack trace is shown below

``Traceback (most recent call last):\n  File \"/projects/matqm/matmethods_env/codes/fireworks/fireworks/core/rocket.py\", line 229, in run\n    m_action = t.run_task(my_spec)\n  File \"/projects/matqm/matmethods_env/codes/atomate/atomate/vasp/firetasks/run_calc.py\", line 185, in run_task\n    c.run()\n  File \"/projects/matqm/matmethods_env/codes/custodian/custodian/custodian.py\", line 323, in run\n    .format(self.total_errors, ex))\nRuntimeError: 5 errors reached: (CustodianError(...), u'MaxErrors'). Exited...\n``

See error file below for more info:
[error_2.tar.gz](https://github.com/materialsproject/custodian/files/924511/error_2.tar.gz)

**Comment by shyuep** [comment]
Note that once max_errors is hit, postprocess is never run. For the first run, it seems to me that the first relaxation actually completed just fine (reached final accuracy). That means max_errors was hit in the second relaxation probably? In fact, custodian.json indicates that the second relaxation was started.

For the second error run, the behavior seems to be as intended. There are 2 errors in relax1, and 3 errors in relax2 in custodian.json. That means you hit the 5 errors in relax2. That is why relax2 has already run....

**Comment by computron** [comment]
>> For the first run, it seems to me that the first relaxation actually completed just fine (reached final accuracy). That means max_errors was hit in the second relaxation probably? In fact, custodian.json indicates that the second relaxation was started.

This doesn't make sense to me given the output files.
- The output files show only one distinct OUTCAR file (there are two files, OUTCAR.relax1 and OUTCAR, but they are the same). If the second relaxation had actually started running, there should be an OUTCAR for the second relaxation somewhere?
- To confirm the above, I also extracted the error.5.tar file. The OUTCAR for that (failed) run started on 2017.03.03  11:57:52. The completed relax1 started on 2017.03.03  21:55:21. So all 5 errors were for relax1.
- To further confirm the above, the custodian.json groups the errors for each relaxation (job). Looking at it, all 5 errors are for the first relaxation.

That said, the 3/3/17 makes me think this was an older custodian version before the "MAX_ERRORS" correction brought up in a previous ticket. So I guess this example is disqualified.

>> For the second error run, the behavior seems to be as intended. There are 2 errors in relax1, and 3 errors in relax2 in custodian.json. That means you hit the 5 errors in relax2. That is why relax2 has already run....

Yes, you are correct. Although it might make sense to allow MAX_ERRORS to be *per job*? e.g., if I have MAX_ERRORS=5, and it took 4 error corrections to get through the first relaxation, but now we're good, I would not want the second relaxation to immediately exit upon the first error and would want custodian to also try to recover the second relaxation. I don't want MAX_ERRORS=10, i.e., I don't want to allow 9 corrections on the first relaxation, but once I am reset to a new job I'd want the counter to be reset.

**Comment by mkhorton** [comment]
> Although it might make sense to allow MAX_ERRORS to be per job? e.g., if I have MAX_ERRORS=5, and it took 4 error corrections to get through the first relaxation, but now we're good, I would not want the second relaxation to immediately exit upon the first error and would want custodian to also try to recover the second relaxation.

+1 for MAX_ERRORS to be per job -- I've been running into this too

**Comment by shyuep** [comment]
I would suggest we do a two cutoff thing. i. Max errors. ii. Max errors per job. Once either criteria is hit, exit. The idea here is that you do not want 4 errors in job 1, and then 4 errors in job 2. That to me sounds like a pretty bad job. 

With this change, you will be able to set a higher max_errors, and a reasonable max errors per job.

**Comment by mkhorton** [comment]
Thanks for adding this.

> That to me sounds like a pretty bad job.

I concede this is often the case!
