### ISSUE TITLE
Unfreezef and Restart option for FEFF calculation

### ISSUE THREAD

**Issue by czhengsci** [materialsproject/custodian#71]
Current FEFF nonconvergence error correction relies on the adjusting of the maximum iterations and convergence accelerator factor. An alternative option, i.e. RESTART card, could be implemented for more robust error correction. If RESTART is specified, FEFF will start the SCF calculation of the potentials from an existing "pot.bin" file, this way one can continue an earlier SCF calculation and saves SCF potential calculation time.

**Comment by shyuep** [comment]
OK. Go ahead and implement.
