### ISSUE TITLE
ALGO=All method for correcting unconverged electronic loops

### ISSUE THREAD

**Issue by computron** [materialsproject/custodian#75]
## System

* Custodian version: master

## Summary

* If a job has not reached electronic converged (UnconvergedErrorHandler), the fix procedure in custodian is:

```
                new_settings = {"ISTART": 1,
                                "ALGO": "Normal",
                                "NELMDL": -6,
                                "BMIX": 0.001,
                                "AMIX_MAG": 0.8,
                                "BMIX_MAG": 0.001} 
```

Recently, I've had pretty good luck with just setting ```ALGO=All``` when a job is unconverged rather than making all these changes (This is in fact how UnconvergedHandler already deals with SCAN failures, but I think it's more general than that). If it were just up to my qualitative assessment, I would first try ```ALGO=All```; if that still doesn't work, to try making all the various changes above.

Downside: I don't have any hard facts to support my case.

Perhaps @shyamd or @montoyjh or @mkhorton or @tschaume can support or deny.

If we do want to switch to trying ALGO=All first, I'd be happy to do the implementation. So it's just a matter of deciding.

**Comment by computron** [comment]
So maybe we want to keep normal as the first step, then simply add "All" as a new step if that one fails. The only issue is that currently custodian is also changing all these various mixing parameters which might mess things up (or might not, who knows)

**Comment by shyuep** [comment]
The choice is ALGO is basically a competition between speed and reliability. As far as I know, no one has done a proper study of the difference in speed between Fast and Normal and All. Specifically, where does Normal fail?

**Comment by shyamd** [comment]
I implement the ladder in case we starts off at something looser. I didn't want to jump from VF to All, for instance, but just incrementally trade off speed and stability until it worked. This might not be the most efficient.

**Comment by mkhorton** [comment]
I'd caution against including VeryFast on the ladder for HT use, it exclusively uses RMM-DIIS which can fail in dangerous ways (it converges, but can converge to an incorrect result).
