### ISSUE TITLE
Check POSCAR under input folder

### ISSUE THREAD

**Issue by shaunrong** [materialsproject/custodian#8]
The VaspCustodianTask function from fireworks_vasp.tasks seems to be checking if there is a poscar under the folder or not.

This becomes a problem when I ran it for the NEB input sets, where all poscars are written in 00~0x sub folders. And there is no poscar under the input file-folder.

VaspCustodianTask(vasp_cmd=['aprun', '-n', '48', '/global/homes/r/rongzq/bin/vasp_5.3.3/vasp_hopper/vasp', '>&', 'stdout'], handlers='all', custodian_params=custodian_params)

**Comment by shyuep** [comment]
Superseded by new vasp input sets.
