### ISSUE TITLE
Temporary modifications to input sets

### ISSUE THREAD

**Issue by wmdrichards** [materialsproject/custodian#9]
Sometimes conjugate gradient doesn't work well for ionic relaxation in VASP. In some cases (mostly with high degrees of freedom, and hard+soft vibrational modes), I have found that the velocity quench algorithm (surprisingly) works better (even though damped MD doesn't help). The simple solution would be to switch the algo with the UnconvergedError handler. However, I think it may be be more effective to switch the algo back to the original (usually conjugate gradient) after the 1st relaxation completes.

Currently, this is difficult within the Custodian framework, as it is a state machine. My proposition is to allow error handlers to prepend actions to a list that runs during job post-processing.

Does anyone have alternative suggestions, or think that this is outside the scope of what Custodian should be able to handle?

**Comment by shyuep** [comment]
I think this is superseded by the new input sets.
