### ISSUE TITLE
Custodian does not print output on jobs that are killed

### ISSUE THREAD

**Issue by sivonxay** [materialsproject/custodian#91]
When running VASP with custodian (using fireworks), custodian errors are printed to the run directory after execution is completed. This is an issue, however, in cases when lots of errors result in a job hitting walltime or when a job gets pre-empted.

Perhaps the custodian log could be updated/written after each correction? This would give preserve the information even if the job is killed suddenly.

**Comment by shyuep** [comment]
As far as I know, the custodian log is written after each correction. Esp the custodian.json file. As for the text logger, that is just output from the logger class in custodian and is customized by the caller itself.
