### ISSUE TITLE
Add convergence handler for meta-GGAs to use LMIXTAU

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/custodian#94]
Try LMIXTAU=True for convergence issues when meta-GGAs are used. Tagging @shyamd in connection to our SCAN work. Further investigation required, but maybe even worth setting by default in the SCAN set?

https://cms.mpi.univie.ac.at/wiki/index.php/LMIXTAU

**Comment by rkingsbury** [comment]
Closing because we set `LMIXTAU=True` in `MPScanRelaxSet`.
